---
name: Refresh Algolia Index

on:
  deployment:

permissions:
  deployments: read

concurrency:
  group: 'algolia-index-refresh'
  cancel-in-progress: true

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event.deployment.environment == 'github-pages' }}
        uses: algolia/algoliasearch-crawler-github-actions@v1.1.10
        id: algolia_crawler
        with: # mandatory parameters
          crawler-user-id: ${{ secrets.CRAWLER_USER_ID }}
          crawler-api-key: ${{ secrets.CRAWLER_API_KEY }}
          algolia-app-id: ${{ secrets.ALGOLIA_APP_ID }}
          algolia-api-key: ${{ secrets.ALGOLIA_API_KEY }}
          crawler-name: 'help-yagpdb'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          site-url: 'https://help.yagpdb.xyz'
